// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.1
// source: libs/shared/src/infrastructure/contracts/proto/audit.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "audit";

export interface HealthRequest {
}

export interface HealthResponse {
  status: string;
}

export interface CreateAuditRecordRequest {
  entityType: string;
  entityId: string;
  action: string;
  actorId: string;
  metadata: string;
}

export interface ListAuditRecordsRequest {
  entityType?: string | undefined;
  entityId?: string | undefined;
}

export interface AuditRecordResponse {
  id: string;
  entityType: string;
  entityId: string;
  action: string;
  actorId: string;
  metadata: string;
  createdAt: string;
}

export interface ListAuditRecordsResponse {
  records: AuditRecordResponse[];
}

export const AUDIT_PACKAGE_NAME = "audit";

export interface AuditServiceClient {
  health(request: HealthRequest): Observable<HealthResponse>;

  createAuditRecord(request: CreateAuditRecordRequest): Observable<AuditRecordResponse>;

  listAuditRecords(request: ListAuditRecordsRequest): Observable<ListAuditRecordsResponse>;
}

export interface AuditServiceController {
  health(request: HealthRequest): Promise<HealthResponse> | Observable<HealthResponse> | HealthResponse;

  createAuditRecord(
    request: CreateAuditRecordRequest,
  ): Promise<AuditRecordResponse> | Observable<AuditRecordResponse> | AuditRecordResponse;

  listAuditRecords(
    request: ListAuditRecordsRequest,
  ): Promise<ListAuditRecordsResponse> | Observable<ListAuditRecordsResponse> | ListAuditRecordsResponse;
}

export function AuditServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["health", "createAuditRecord", "listAuditRecords"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuditService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuditService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUDIT_SERVICE_NAME = "AuditService";
