// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.1
// source: libs/shared/src/infrastructure/contracts/proto/clients.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "clients";

export interface HealthRequest {
}

export interface HealthResponse {
  status: string;
}

export interface ListClientsRequest {
}

export interface GetClientRequest {
  id: string;
}

export interface CreateClientRequest {
  name: string;
  email: string;
  phone: string;
  address: string;
}

export interface UpdateClientRequest {
  id: string;
  name?: string | undefined;
  email?: string | undefined;
  phone?: string | undefined;
  address?: string | undefined;
  active?: boolean | undefined;
}

export interface DeleteClientRequest {
  id: string;
}

export interface DeleteClientResponse {
  deleted: boolean;
}

export interface ClientResponse {
  id: string;
  name: string;
  email: string;
  phone: string;
  address: string;
  active: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ListClientsResponse {
  clients: ClientResponse[];
}

export const CLIENTS_PACKAGE_NAME = "clients";

export interface ClientsServiceClient {
  health(request: HealthRequest): Observable<HealthResponse>;

  listClients(request: ListClientsRequest): Observable<ListClientsResponse>;

  getClient(request: GetClientRequest): Observable<ClientResponse>;

  createClient(request: CreateClientRequest): Observable<ClientResponse>;

  updateClient(request: UpdateClientRequest): Observable<ClientResponse>;

  deleteClient(request: DeleteClientRequest): Observable<DeleteClientResponse>;
}

export interface ClientsServiceController {
  health(request: HealthRequest): Promise<HealthResponse> | Observable<HealthResponse> | HealthResponse;

  listClients(
    request: ListClientsRequest,
  ): Promise<ListClientsResponse> | Observable<ListClientsResponse> | ListClientsResponse;

  getClient(request: GetClientRequest): Promise<ClientResponse> | Observable<ClientResponse> | ClientResponse;

  createClient(request: CreateClientRequest): Promise<ClientResponse> | Observable<ClientResponse> | ClientResponse;

  updateClient(request: UpdateClientRequest): Promise<ClientResponse> | Observable<ClientResponse> | ClientResponse;

  deleteClient(
    request: DeleteClientRequest,
  ): Promise<DeleteClientResponse> | Observable<DeleteClientResponse> | DeleteClientResponse;
}

export function ClientsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "health",
      "listClients",
      "getClient",
      "createClient",
      "updateClient",
      "deleteClient",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ClientsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ClientsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CLIENTS_SERVICE_NAME = "ClientsService";
