// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.1
// source: libs/shared/src/infrastructure/contracts/proto/packages.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "packages";

export interface HealthRequest {
}

export interface HealthResponse {
  status: string;
}

export interface ListPackagesRequest {
  page: number;
  limit: number;
  status?: string | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
}

export interface GetPackageRequest {
  id: string;
}

export interface GetPackageByTrackingCodeRequest {
  trackingCode: string;
}

export interface ListPackagesByClientRequest {
  clientId: string;
  page: number;
  limit: number;
  status?: string | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
}

export interface CreatePackageRequest {
  clientId: string;
  description: string;
  destinationAddress: string;
  changedBy: string;
}

export interface UpdatePackageRequest {
  id: string;
  description?: string | undefined;
  destinationAddress?: string | undefined;
}

export interface UpdatePackageStatusRequest {
  id: string;
  status: string;
  changedBy: string;
  comment?: string | undefined;
}

export interface DeletePackageRequest {
  id: string;
}

export interface DeletePackageResponse {
  deleted: boolean;
}

export interface PackageHistoryResponse {
  id: string;
  status: string;
  comment?: string | undefined;
  changedAt: string;
  changedBy: string;
}

export interface PackageResponse {
  id: string;
  trackingCode: string;
  clientId: string;
  description: string;
  destinationAddress: string;
  status: string;
  history: PackageHistoryResponse[];
  createdAt: string;
  updatedAt: string;
}

export interface ListPackagesResponse {
  packages: PackageResponse[];
  page: number;
  limit: number;
  total: number;
  totalPages: number;
}

export interface PackageStatusStatsRequest {
  startDate: string;
  endDate: string;
}

export interface PackageStatusStatItem {
  status: string;
  total: number;
}

export interface PackageStatusStatsResponse {
  items: PackageStatusStatItem[];
  total: number;
  startDate: string;
  endDate: string;
}

export const PACKAGES_PACKAGE_NAME = "packages";

export interface PackagesServiceClient {
  health(request: HealthRequest): Observable<HealthResponse>;

  listPackages(request: ListPackagesRequest): Observable<ListPackagesResponse>;

  listPackagesByClient(request: ListPackagesByClientRequest): Observable<ListPackagesResponse>;

  getPackage(request: GetPackageRequest): Observable<PackageResponse>;

  getPackageByTrackingCode(request: GetPackageByTrackingCodeRequest): Observable<PackageResponse>;

  createPackage(request: CreatePackageRequest): Observable<PackageResponse>;

  updatePackage(request: UpdatePackageRequest): Observable<PackageResponse>;

  updatePackageStatus(request: UpdatePackageStatusRequest): Observable<PackageResponse>;

  deletePackage(request: DeletePackageRequest): Observable<DeletePackageResponse>;

  getStatusStats(request: PackageStatusStatsRequest): Observable<PackageStatusStatsResponse>;
}

export interface PackagesServiceController {
  health(request: HealthRequest): Promise<HealthResponse> | Observable<HealthResponse> | HealthResponse;

  listPackages(
    request: ListPackagesRequest,
  ): Promise<ListPackagesResponse> | Observable<ListPackagesResponse> | ListPackagesResponse;

  listPackagesByClient(
    request: ListPackagesByClientRequest,
  ): Promise<ListPackagesResponse> | Observable<ListPackagesResponse> | ListPackagesResponse;

  getPackage(request: GetPackageRequest): Promise<PackageResponse> | Observable<PackageResponse> | PackageResponse;

  getPackageByTrackingCode(
    request: GetPackageByTrackingCodeRequest,
  ): Promise<PackageResponse> | Observable<PackageResponse> | PackageResponse;

  createPackage(
    request: CreatePackageRequest,
  ): Promise<PackageResponse> | Observable<PackageResponse> | PackageResponse;

  updatePackage(
    request: UpdatePackageRequest,
  ): Promise<PackageResponse> | Observable<PackageResponse> | PackageResponse;

  updatePackageStatus(
    request: UpdatePackageStatusRequest,
  ): Promise<PackageResponse> | Observable<PackageResponse> | PackageResponse;

  deletePackage(
    request: DeletePackageRequest,
  ): Promise<DeletePackageResponse> | Observable<DeletePackageResponse> | DeletePackageResponse;

  getStatusStats(
    request: PackageStatusStatsRequest,
  ): Promise<PackageStatusStatsResponse> | Observable<PackageStatusStatsResponse> | PackageStatusStatsResponse;
}

export function PackagesServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "health",
      "listPackages",
      "listPackagesByClient",
      "getPackage",
      "getPackageByTrackingCode",
      "createPackage",
      "updatePackage",
      "updatePackageStatus",
      "deletePackage",
      "getStatusStats",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PackagesService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PackagesService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PACKAGES_SERVICE_NAME = "PackagesService";
