// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.1
// source: libs/shared/src/infrastructure/contracts/proto/package-status.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "package_status";

export interface HealthRequest {
}

export interface HealthResponse {
  status: string;
}

export interface GetPackageStatusRequest {
  id: string;
}

export interface TrackPackageStatusRequest {
  trackingCode: string;
  email: string;
}

export interface PackageStatusHistoryResponse {
  id: string;
  status: string;
  comment?: string | undefined;
  changedAt: string;
  changedBy: string;
}

export interface PackageStatusResponse {
  id: string;
  trackingCode: string;
  status: string;
  history: PackageStatusHistoryResponse[];
  updatedAt: string;
  clientId: string;
}

export const PACKAGE_STATUS_PACKAGE_NAME = "package_status";

export interface PackageStatusServiceClient {
  health(request: HealthRequest): Observable<HealthResponse>;

  getPackageStatus(request: GetPackageStatusRequest): Observable<PackageStatusResponse>;

  trackPackageStatus(request: TrackPackageStatusRequest): Observable<PackageStatusResponse>;
}

export interface PackageStatusServiceController {
  health(request: HealthRequest): Promise<HealthResponse> | Observable<HealthResponse> | HealthResponse;

  getPackageStatus(
    request: GetPackageStatusRequest,
  ): Promise<PackageStatusResponse> | Observable<PackageStatusResponse> | PackageStatusResponse;

  trackPackageStatus(request: TrackPackageStatusRequest): Observable<PackageStatusResponse>;
}

export function PackageStatusServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["health", "getPackageStatus", "trackPackageStatus"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PackageStatusService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PackageStatusService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PACKAGE_STATUS_SERVICE_NAME = "PackageStatusService";
