// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.1
// source: libs/shared/src/infrastructure/contracts/proto/users.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "users";

export interface HealthRequest {
}

export interface HealthResponse {
  status: string;
}

export interface GetUserByEmailRequest {
  email: string;
}

export interface GetUserByIdRequest {
  id: string;
}

export interface UserResponse {
  id: string;
  email: string;
  passwordHash: string;
  name: string;
  role: string;
  createdAt: string;
  updatedAt: string;
  clientId?: string | undefined;
}

export interface CreateClientUserRequest {
  email: string;
  passwordHash: string;
  name: string;
  clientId: string;
}

export const USERS_PACKAGE_NAME = "users";

export interface UsersServiceClient {
  health(request: HealthRequest): Observable<HealthResponse>;

  getUserByEmail(request: GetUserByEmailRequest): Observable<UserResponse>;

  getUserById(request: GetUserByIdRequest): Observable<UserResponse>;

  createClientUser(request: CreateClientUserRequest): Observable<UserResponse>;
}

export interface UsersServiceController {
  health(request: HealthRequest): Promise<HealthResponse> | Observable<HealthResponse> | HealthResponse;

  getUserByEmail(request: GetUserByEmailRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  getUserById(request: GetUserByIdRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  createClientUser(request: CreateClientUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;
}

export function UsersServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["health", "getUserByEmail", "getUserById", "createClientUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USERS_SERVICE_NAME = "UsersService";
