// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.1
// source: libs/shared/src/infrastructure/contracts/proto/users.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "users";

export interface HealthRequest {
}

export interface HealthResponse {
  status: string;
}

export interface GetUserByEmailRequest {
  email: string;
}

export interface GetUserByIdRequest {
  id: string;
}

export interface UserResponse {
  id: string;
  email: string;
  passwordHash: string;
  name: string;
  role: string;
  createdAt: string;
  updatedAt: string;
  clientId?: string | undefined;
  active: boolean;
}

export interface CreateClientUserRequest {
  email: string;
  passwordHash: string;
  name: string;
  clientId: string;
}

export interface ListRegisteredClientIdsRequest {
  clientIds: string[];
}

export interface ListRegisteredClientIdsResponse {
  clientIds: string[];
}

export interface CountRegisteredClientsRequest {
}

export interface CountRegisteredClientsResponse {
  total: number;
}

export interface ListOperatorsRequest {
  page: number;
  limit: number;
}

export interface ListOperatorsResponse {
  users: UserResponse[];
  page: number;
  limit: number;
  total: number;
  totalPages: number;
}

export interface CreateOperatorRequest {
  email: string;
  password: string;
  name: string;
}

export interface RevokeOperatorAccessRequest {
  id: string;
}

export interface UpdateProfileRequest {
  id: string;
  name: string;
}

export interface ChangePasswordRequest {
  id: string;
  currentPassword: string;
  newPassword: string;
}

export const USERS_PACKAGE_NAME = "users";

export interface UsersServiceClient {
  health(request: HealthRequest): Observable<HealthResponse>;

  getUserByEmail(request: GetUserByEmailRequest): Observable<UserResponse>;

  getUserById(request: GetUserByIdRequest): Observable<UserResponse>;

  createClientUser(request: CreateClientUserRequest): Observable<UserResponse>;

  listRegisteredClientIds(request: ListRegisteredClientIdsRequest): Observable<ListRegisteredClientIdsResponse>;

  countRegisteredClients(request: CountRegisteredClientsRequest): Observable<CountRegisteredClientsResponse>;

  listOperators(request: ListOperatorsRequest): Observable<ListOperatorsResponse>;

  createOperator(request: CreateOperatorRequest): Observable<UserResponse>;

  revokeOperatorAccess(request: RevokeOperatorAccessRequest): Observable<UserResponse>;

  updateProfile(request: UpdateProfileRequest): Observable<UserResponse>;

  changePassword(request: ChangePasswordRequest): Observable<UserResponse>;
}

export interface UsersServiceController {
  health(request: HealthRequest): Promise<HealthResponse> | Observable<HealthResponse> | HealthResponse;

  getUserByEmail(request: GetUserByEmailRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  getUserById(request: GetUserByIdRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  createClientUser(request: CreateClientUserRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  listRegisteredClientIds(
    request: ListRegisteredClientIdsRequest,
  ): Promise<ListRegisteredClientIdsResponse> | Observable<ListRegisteredClientIdsResponse> | ListRegisteredClientIdsResponse;

  countRegisteredClients(
    request: CountRegisteredClientsRequest,
  ): Promise<CountRegisteredClientsResponse> | Observable<CountRegisteredClientsResponse> | CountRegisteredClientsResponse;

  listOperators(
    request: ListOperatorsRequest,
  ): Promise<ListOperatorsResponse> | Observable<ListOperatorsResponse> | ListOperatorsResponse;

  createOperator(request: CreateOperatorRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  revokeOperatorAccess(
    request: RevokeOperatorAccessRequest,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  updateProfile(request: UpdateProfileRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  changePassword(request: ChangePasswordRequest): Promise<UserResponse> | Observable<UserResponse> | UserResponse;
}

export function UsersServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "health",
      "getUserByEmail",
      "getUserById",
      "createClientUser",
      "listRegisteredClientIds",
      "countRegisteredClients",
      "listOperators",
      "createOperator",
      "revokeOperatorAccess",
      "updateProfile",
      "changePassword",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UsersService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USERS_SERVICE_NAME = "UsersService";
